FROM node:20-alpine
WORKDIR /frontend
RUN yarn global add pnpm
COPY package.json pnpm-lock.yaml .
RUN pnpm i
COPY next-env.d.ts next.config.js postcss.config.js tailwind.config.ts tsconfig.json .
COPY public ./public
COPY src ./src

CMD ["pnpm", "dev"]