services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
