# 開発環境用の設定

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/frontend
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/backend
