version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - frontend_next:/frontend/.next
      - frontend_node_modules:/frontend/node_modules
    command: pnpm start
    tty: true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 9090:9090
    working_dir: /backend
    command: ./backend

volumes:
  frontend_next:
  frontend_node_modules:
