services:
  frontend:
    ports:
      - 3000:${FRONTEND_PORT}
    depends_on:
      - backend
    environment:
      - BACKEND_PORT
  backend:
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - BACKEND_PORT
      - DB_PORT
  db:
    image: postgres:16-alpine
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
