version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    command: pnpm dev
    tty: true
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 9090:9090
    working_dir: /backend
    command: ./backend
