// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type Todo struct {
	ID     int     `json:"id"`
	Text   *string `json:"text,omitempty"`
	Done   *bool   `json:"done,omitempty"`
	UserID *int    `json:"userId,omitempty"`
	User   *User   `json:"user,omitempty"`
}

type User struct {
	ID   int     `json:"id"`
	Name *string `json:"name,omitempty"`
}
